name: Python code checks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check_code:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install python-dateutil requests semantic-version six websocket_client
    - name: Lint with pylint
      run: |
        pip install pylint
        # exit-zero treats all errors as warnings
        pylint * --exit-zero
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings
        flake8 . --count --exit-zero --statistics
